# Generated by Django 5.0.7 on 2024-07-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='meals',
            new_name='meal',
        ),
    ]
